import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,advance,action,chamber,validate,rate} from '../../public/living-mine-beta/engine.js';
import worker from '../../src/index.js';import {LivingMinePlayer,handleLivingMine} from '../../src/living-mine.js';import {makeSession} from '../../src/_session.js';
test('new mine has positive production and optional manual mining',()=>{const s=fresh(4,1000);assert.ok(rate(s)>0);assert.equal(action(s,{type:'mine'},2000).swings,1);assert.ok(advance(s,61000).earned>0);});
test('offline and partitioned simulation agree including discoveries',()=>{const s=fresh(4,1000);const once=advance(s,601000).state;let tick=s;for(let n=2000;n<=601000;n+=1000)tick=advance(tick,n).state;assert.ok(Math.abs(tick.cash-once.cash)<1e-6);assert.equal(tick.journal.length,once.journal.length);});
test('construction splits production and completes offline',()=>{let s=fresh(4,1000);s.cash=1000;s=action(s,{type:'build',id:'workshop'},1000);const a=advance(s,61000).state;assert.equal(a.buildings.workshop,1);assert.equal(a.construction,null);assert.ok(a.lifetime>60);});
test('clock rollback never earns resources or rewinds timestamp',()=>{const s=fresh(4,1000);assert.equal(advance(s,500).earned,0);assert.equal(advance(s,500).state.last,1000);});
test('offline storage cap and no double reward after refresh',()=>{const s=fresh(4,1000),r=advance(s,1000+86400000);assert.equal(r.seconds,28800);assert.equal(r.state.ore,3000);assert.equal(advance(r.state,r.state.last).earned,0);});
test('balanced affordable progression and connected seeded world',()=>{for(let seed=0;seed<1000;seed++){for(let i=0;i<24;i++){const a=chamber(seed,i);assert.deepEqual(a,chamber(seed,i));if(i)assert.ok(a.parent>=0&&a.parent<i);}}let s=fresh(4,1000);s=action(s,{type:'hire'},1000);assert.equal(s.miners,2);assert.ok(s.cash>=0);s.cash=10000;for(let i=0;i<2;i++)s=action(s,{type:'explore'},1000);assert.throws(()=>action(s,{type:'explore'},1000));s=action(s,{type:'shaft'},1000);s=action(s,{type:'explore'},1000);validate(s);});
test('invalid spending, saves and duplicate contracts rejected',()=>{let s=fresh(4,1000);assert.throws(()=>action(s,{type:'rig'},1000));assert.throws(()=>action(s,{type:'build',id:'__proto__'},1000));assert.throws(()=>validate({...s,cash:NaN}));assert.throws(()=>validate({...s,chambers:[{id:0}]}));s.lifetime=150;s=action(s,{type:'contract',id:'first-haul'},1000);assert.throws(()=>action(s,{type:'contract',id:'first-haul'},1000));});
function object(){const map=new Map;let queue=Promise.resolve();const tx={get:async k=>structuredClone(map.get(k)),put:async(k,v)=>map.set(k,structuredClone(v))};return {instance:new LivingMinePlayer({storage:{transaction:fn=>{const p=queue.then(()=>fn(tx));queue=p.catch(()=>{});return p;}}}),map};}
test('authoritative object ignores client balances, deduplicates and checks revisions',async()=>{const {instance,map}=object();await instance.fetch(new Request('https://mine.test/api/living-mine/state'));const body={requestId:'abcdefgh-1234',revision:0,cash:1e9,action:{type:'hire'}};const req=()=>new Request('https://mine.test/api/living-mine/action',{method:'POST',body:JSON.stringify(body)});const results=await Promise.all([instance.fetch(req()),instance.fetch(req())]);assert.ok(results.every(r=>r.status===200));assert.equal(map.get('state').miners,2);assert.ok(map.get('state').cash<10);body.requestId='abcdefgh-5678';assert.equal((await instance.fetch(req())).status,409);});
test('API rejects cross-origin, unauthenticated, wrong method and malformed inputs',async()=>{const env={LIVING_MINE:{},SESSION_SECRET:'test-secret'};assert.equal((await handleLivingMine(new Request('https://mine.test/api/living-mine/state'),env)).status,401);assert.equal((await handleLivingMine(new Request('https://mine.test/api/living-mine/action',{method:'POST',headers:{origin:'https://evil.test'}}),env)).status,403);assert.equal((await handleLivingMine(new Request('https://mine.test/api/living-mine/state',{method:'POST'}),env)).status,405);const cookie='idledepths='+await makeSession({id:'123',username:'Miner'},env.SESSION_SECRET);assert.equal((await handleLivingMine(new Request('https://mine.test/api/living-mine/action',{method:'POST',headers:{origin:'https://mine.test',cookie,'content-type':'application/json'},body:'x'.repeat(2049)}),env)).status,413);});
test('production static and API routing remain unchanged',async()=>{let called=false;const r=await worker.fetch(new Request('https://mine.test/'),{ASSETS:{fetch:()=>{called=true;return new Response('production');}}});assert.equal(await r.text(),'production');assert.ok(called);const me=await worker.fetch(new Request('https://mine.test/api/me'),{});assert.equal(await me.json(),null);const beta=await worker.fetch(new Request('https://mine.test/api/living-mine/state'),{});assert.equal(beta.status,503);});
test('epoch timestamp precision cannot stall offline events',()=>{const now=1791447010000;const s=fresh(144,now-3600000);s.shafts=4;s.chambers=Array.from({length:12},(_,i)=>chamber(s.seed,i));s.construction={id:'workshop',ends:now-1000};const r=advance(s,now).state;assert.equal(r.construction,null);assert.equal(r.buildings.workshop,1);assert.ok(r.lifetime>2000);});
test('server rate limit and damaged-save protection',async()=>{const {instance,map}=object();map.set('state',{broken:true});const req=()=>new Request('https://mine.test/api/living-mine/state');assert.equal((await instance.fetch(req())).status,409);assert.deepEqual(map.get('state'),{broken:true});map.delete('state');for(let i=0;i<7;i++)await instance.fetch(req());assert.equal((await instance.fetch(req())).status,429);});
